[package]
name = "tls-client"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
hkdf = "0.12.4"

sha2 = "0.10.9"
# x25519-dalek = {version = "2.0.1", features = ["static_secrets","getrandom"] }

curve25519-dalek = "5.0.0-pre.0"
rust-crypto = "=0.2.36"
rand = "0.9.2"


